### ISSUE TITLE
 Please add a LICENSE to clarify licensing

### ISSUE THREAD

**Issue by janreggie** [sajanraj/SLRGUI#1]
Please put a LICENSE in the top-level directory so potential users and contributors understand the licensing of this project.

We're currently reading on your paper (*Indian Sign Language Numeral Recognition Using Region of Interest Convolutional Neural Network*) for our undergraduate thesis. Would love to improve what you and Ms. Beena have done, but that may need a [license](https://choosealicense.com/) that allows us to use and improve your code.

**Comment by sajanraj** [comment]
Added Licence
